#!/bin/sh
GRAPH="lua pantograph/main.lua"

FPS="30"
SCALE="2"
INPUT_FILES=""
OUTPUT_FILE="export.mp4"
TEST_MODE=""

PARSED=$(getopt --longoptions "output:,fps:,scale:,help,test" -- "r:o:h" "$@")
eval set -- "$PARSED"

while true; do
	case "$1" in
		-o|--output)
			OUTPUT_FILE="$2"
			shift 2
		;;
		-r|--fps)
			FPS="$2"
			shift 2
		;;
		--scale)
			SCALE="$2"
			shift 2
		;;
		--)
			shift
			INPUT_FILES="$@"
			break
		;;
		-h|--help)
			echo "Pantograph - Programmatic SVG and animation engine"
			echo "  Usage:"
			echo "  $NAME [--fps fps] [--output outputfile] files"
			exit
		;;
		--test)
			TEST_MODE="true"
			shift
		;;
		*)
			shift
		;;
	esac
done

test_animation() {
	$GRAPH --fps "$FPS" --scale "$SCALE" --test $INPUT_FILES
}

export_animation() {
	[ -n "$TEST_MODE" ] && exit
	echo "Rendering..."
	EXPORT="ffmpeg -hide_banner -y -r $FPS -i - -b:v 2M -pix_fmt yuv420p -vcodec libx264"
	$GRAPH --fps "$FPS" --scale "$SCALE" $INPUT_FILES | $EXPORT "$OUTPUT_FILE"
}

test_animation && export_animation
